### ISSUE TITLE
Doesn't work on the Steam Deck

### ISSUE THREAD

**Issue by Neyami** [BlueAmulet/EDFModLoader#6]
Any chance you could make it work on the Steam Deck? :ayaya:

**Comment by BlueAmulet** [comment]
I don't own a Steam Deck so it's hard for me to test on that. Do you have any more info as to what is going wrong?

**Comment by Neyami** [comment]
Oh, well it's linux based so that's probably the reason ^^
There is an .exe file though, so I thought it would work.

**Comment by Neyami** [comment]
After checking the other issues I saw this:
https://github.com/BlueAmulet/EDFModLoader/issues/5

Adding `WINEDLLOVERRIDES="winmm=n,b" %command%` to the launch command for the game does indeed make it work 😀
