### ISSUE TITLE
ChangeFOV patch for EDF6

### ISSUE THREAD

**Issue by tojnk** [BlueAmulet/EDFModLoader#7]
I noticed the ModLoader just got updated for EDF6, great!

So I tried to write a ChangeFOV patch for EDF6 based on this post: https://steamcommunity.com/app/2291060/discussions/0/4509876314624934423/?ctp=3#c4509876314626036196

I extracted the latest release, placed the Patcher.dll
And put the following lines in ChangeFOV.txt and put it in the Patches folder

;1760410: DB 0F 49 3F ; Default (45 vFOV)
1760410: 00 00 80 3F ; 1.0 (57 vFOV)

But it does not work... log show it is loaded, and when I manually edit the EDF.dll it does work... so what could be going wrong here?

**Comment by BlueAmulet** [comment]
Patcher takes memory addresses which differ slightly from file offsets, depending on where you are in the file, you'll have to add different amounts to the address when porting to Patcher.

```
EDF 6 (EDF.dll) Patcher Offsets:
      0 to 174F9FF: +C00
174FA00 to 1F4D5FF: +1600
1F4D600 to 20ABC00: +1A00
```
In your case you'd by adjusting the offset by 0x1600 from 1760410 to 1761A10

But also that is just an awful FOV patch, changing the constant directly affects everything that uses it and not just the FOV code. I'll try to make a better patch that has less chance of unintentional breakage.

**Comment by tojnk** [comment]
Awesome, this works! 
Just out of curiosity what causes these different offsets between memory addresses and file offsets?

**Comment by BlueAmulet** [comment]
Different alignments. EXEs and DLLs are composed of sections, but as a file each section must be aligned to 512 bytes, and in memory each section must be loaded to an aligned address of 4096 bytes. The data can be more tightly packed as a file and ends up spread out more when loaded.
